name: Update Obsidian Help Index

on:
  # once a month (14:14 at the 14th of the month)
  schedule:
    - cron: "14 14 14 * *"

  # triggering manually
  workflow_dispatch:

  # when this file or the script for re-indexing is changed
  push:
    paths:
      - .github/workflows/update-obsidian-help-index.yml
      - scripts/manual-docs-searches/build-obsidian-help-index.mjs

permissions:
  contents: write

#───────────────────────────────────────────────────────────────────────────────

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: update documentation search index
        run: |
          for i in {1..5}; do
            echo "Attempt #$i"
            node ./scripts/manual-docs-searches/build-obsidian-help-index.mjs && exit 0
            sleep 30
          done
          echo "Multiple attempts to re-index the Obsidian docs failed. Aborting."
          exit 1

      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Updated documentation index"
          branch: ${{ github.head_ref }}
