name: Update DevDocs Versions

on:
  # once a month (14:14 at the 14th of the month)
  schedule:
    - cron: "14 14 14 * *"

  # allow triggering manually
  workflow_dispatch: {}

permissions:
  contents: write

#───────────────────────────────────────────────────────────────────────────────

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "21.x"

      - name: Update Documentation Search Index
        run: |
          node ./devdocs/update-available-devdocs.mjs
          git add --all
          [[ -z "$(git status --short)" ]] && exit 0 # no update needed
          git commit -m "chore: Updated devdocs versions" --author="🤖 Automated GitHub Action<cron@job>"
          git push
