name: Update Obsidian Help Index

on:
  schedule:
    # INFO 2h later than the auto-update of devdocs to avoid commit conflicts
    - cron: "15 4 2,15 * *" # twice per month (4:15 at the 2nd and 15th of the month)

  workflow_dispatch: # triggering manually

  push:
    paths: # when this file or the script for re-indexing is changed
      - .github/workflows/update-obsidian-help-index.yml
      - scripts/manual-docs-searches/build-obsidian-help-index.mjs
    branches:
      - main # prevents triggering on temporary branches created when making a release

permissions:
  contents: write

#───────────────────────────────────────────────────────────────────────────────

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup node
        uses: actions/setup-node@v5
        with:
          node-version: "23.x"

      - name: update documentation search index
        env:
          # https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node ./scripts/manual-docs-searches/build-obsidian-help-index.mjs
          exit $? # inherit exit code

      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: auto-update Obsidian help index"
          branch: ${{ github.head_ref }}
