name: Update Devdocs

on:
  # once a month (14:14 at the 14th of the month)
  schedule:
    - cron: "14 14 14 * *"

  # allow triggering manually
  workflow_dispatch:

permissions:
  contents: write

#───────────────────────────────────────────────────────────────────────────────

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "21.x" }
      - name: Update Devdocs
        run: |
          node ./devdocs/update-available-devdocs.mjs

          # GUARD if only the `info.plist` was updated, it's due to formatting changes
          # and there is not actual update to be made.
          updated_files=$(git diff --staged --name-only)
          [[ ! "$updated_files" =~ keyword-slug-map ]] && exit 0

          # determine what changes occurred and add them to the commit message
          changes=$(
          	git diff --staged -- .github/keyword-slug-map.json |
          		tail +6 |                                     # remove diff header
          		tr "," "\n" |                                 # split into new lines
          		sed -Ee 's/[+-]{//' -Ee 's/".*":"(.*)"/\1/' | # remove json/diff syntax
          		grep -v "No newline at end of file" |
          		sort |           # needed for `uniq`
              uniq -u |        # `-u`: only lines appearing once
          		awk 'ORS=", "' | # merge lines with commas
          		sed -e 's/, $//' # remove trailing comma
          )

          git commit --message "chore: update devdocs ($changes)" \
              --author="🤖 Automated GitHub Action<cron@job>"
          git push
