name: Update DevDocs Versions

on:
  # once a month (14:14 at the 14th of the month)
  schedule:
    - cron: "14 14 14 * *"

  # allow triggering manually
  workflow_dispatch:

permissions:
  contents: write

#───────────────────────────────────────────────────────────────────────────────

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "21.x" }
      - name: Update Documentation Search Index
        run: |
          # INFO the script also updated the `info.plist` popup selection,
          # however we do not add those here as they complicate updates with
          # my local Alfred workflow. This auto-updating workflow is for now
          # only concerned with updating the keyword-slug-map.json file, and the
          # `info.plist` can be manually updated (since it will require an
          # update much less frequently anyway).
          node ./devdocs/update-available-devdocs.mjs
          git add ./.github/keyword-slug-map.json

          [[ -z "$(git diff --staged --name-only)" ]] && exit 0 # no update needed

          # determine what changes occurred and add them to the commit message
          changes=$(
          	git diff --staged -- .github/keyword-slug-map.json |
          		tail +6 |                                     # remove diff header
          		tr "," "\n" |                                 # split into new lines
          		sed -Ee 's/[+-]{//' -Ee 's/".*":"(.*)"/\1/' | # remove json/diff syntax
          		grep -v "No newline at end of file" |
          		sort |           # needed for `uniq`
          		uniq -u |        # `-u` only lines appearing once
          		awk 'ORS=", "' | # merge lines with commas
          		sed -e 's/, $//' # remove trailing comma
          )

          git commit --message "chore: update devdocs ($changes)" \
              --author="🤖 Automated GitHub Action<cron@job>"
          git push
