name: Update Devdocs

on:
  # twice per month (2:15 at the 2nd and 15th of the month)
  schedule:
    - cron: "15 2 2,15 * *"

  # manual triggering
  workflow_dispatch:

  # on updates to this file or the update script
  push:
    paths:
      - .github/workflows/update-devdocs.yml
      - scripts/devdocs/update-devdocs.mjs

permissions:
  contents: write

#───────────────────────────────────────────────────────────────────────────────

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "22.x" }
      - name: Update devdocs
        run: |
          node ./scripts/devdocs/update-devdocs.mjs

          # GUARD if only the `info.plist` was updated, it's due to formatting changes
          # and there is not actual update to be made.
          updated_files=$(git diff --name-only)
          [[ ! "$updated_files" =~ keyword-slug-map ]] && exit 0

          # determine what changes occurred and add them to the commit message
          changes=$(
          	git diff .github/keyword-slug-map.json |
          		tail +6 |                                     # remove diff header
          		tr "," "\n" |                                 # split into new lines
          		sed -Ee 's/[+-]{//' -Ee 's/".*":"(.*)"/\1/' | # remove json/diff syntax
          		grep -v "No newline at end of file" |
          		sort |           # needed for `uniq`
              uniq -u |        # `-u`: only lines appearing once
          		awk 'ORS=", "' | # merge lines with commas
          		sed -e 's/, $//' # remove trailing comma
          )
          # do not stop workflow here, just indicate that the change detection
          # has an issue
          [[ -z "$changes" ]] && changes="???"

          git add --all
          git commit --message "chore: update devdocs ($changes)" \
              --author="🤖 Automated GitHub Action<cron@job>"
          git push
